
function loso()
% You can run the code without any input arguments

% It loads the generalCounterMatrixFaces.mat file generated by Elena's read
% code, or you can change that to generalCounterMatrixCropFaces.mat to use
% crop faces
load generalCounterMatrixFaces.mat;

[subject_no, emotion_no] = size(matrix_faces);

    trial_matrix = cell(subject_no,1);
    for subject_id=1:subject_no
        % produce a train and test set for every subject one by one
        [train_set,test_set] = produce_one_test(subject_id, matrix_faces, general_counter);
        trial_matrix{subject_id,1}.train = train_set;
        trial_matrix{subject_id,1}.test = test_set;
    end
    
    % This code creates a mat file which contains all the trial sets (test+train)
    save trials.mat trial_matrix;
end

function [train_set, test_set] = produce_one_test(subject_id, matrix_faces, counter)
        [x,y] = size(matrix_faces);

        test_counter = 1;
        train_counter = 1;

        for index_x=1:x
            for index_y=1:y
                total_face = counter(index_x, index_y);
                if(subject_id==index_x)
                    for counter_index = 1:total_face
                        test_set{test_counter,1}.picture = matrix_faces{index_x,index_y}.entire_picture(:,counter_index);
                        test_set{test_counter,1}.emotion = index_y;
                        test_counter = test_counter + 1;
                    end
                else
                    for counter_index = 1:total_face
                        train_set{train_counter,1}.picture = matrix_faces{index_x,index_y}.entire_picture(:,counter_index);
                        train_set{train_counter,1}.emotion = index_x;
                        train_counter = train_counter + 1;
                    end
                end
            end
        end
end